- name: Configure DB Image
  hosts: all
  become: true
  tasks:
  - name: Add an apt key by id from a keyserver
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: EA312927
      state: present

  - apt_repository:
      repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      filename: /etc/apt/sources.list.d/mongodb-org-3.2.list
      update_cache: yes
      state: present    

  - name: Install the package "mongodb-org"
    apt:
      name: mongodb-org
      force: yes
      state: present

  - name: enable/start mongod
    systemd:
      name: mongod
      enabled: yes
      state: started
     
